[package]
name = "rstdms"
version = "0.1.0"
authors = ["Adam Reeve <adreeve@gmail.com>"]
edition = "2018"

[dependencies]
num_enum = "0.5.1"
typed-arena = "2.0.1"

[dev-dependencies]
hex-literal = "0.3.1"
