[package]
name = "rstdms"
version = "0.1.0"
authors = ["Adam Reeve <adreeve@gmail.com>"]
edition = "2018"

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
thiserror = "1.0"

[dev-dependencies]
hex-literal = "0.3.1"

