[package]
name = "rstdms"
version = "0.1.0"
authors = ["Adam Reeve <adreeve@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
hex-literal = "0.3.1"
